site:
  site_verification:
  beian: 滇ICP备18008444号-2
  page_title: 人可能走了，但代码还在...

menu:
  Home: .
  Archives: archives
  Tags: tags
  Links: links
  About: about
  Site: site

menu_icons:
  home: pure-home
  archives: pure-archive
  tags: pure-tags
  links: pure-leaf
  about: pure-cafe
  site: pure-flask

profile:
  avatar: images/avatar.png
  author: Carey Q
  author_title: Code changes itself.
  author_description: 个人简介。
  location: Yunnan, China
  follow: /
  social:
    github: https://github.com/CareyQ
    mail: mailto:careyq03@gmail.com
    rss: atom.xml
  skills:
    Java: ★★★★☆
    Spring: ★★★☆☆
    Git: ★★★☆☆
    SQL: ★★★☆☆
    Linux: ★★★☆☆
    HTML + CSS: ★★★★☆
    Javascript: ★★☆☆☆
    Happy: ★★★★★

  labels:
    - Java 开发
    - 折腾系
    - 模拟游戏玩家
    - 代码菜狗